import { useState } from "react";
import {
  aiRequirements, aiUserStories, aiArchitecture, aiRisks, erdMermaid,
  personById, lifecycleStages, type Project,
} from "../data/mock";
import { useApp } from "../AppContext";
import { Panel, AiTag, Mono, StatusPill, money, ProgressBar } from "./shared";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "./ui/tabs";
import { cn } from "./ui/utils";
import {
  FileText, ListTree, Network, Database, CalendarRange, ShieldAlert,
  DollarSign, Check, Pencil,
} from "lucide-react";

function Stepper({ status }: { status: Project["status"] }) {
  const idx = lifecycleStages.findIndex((s) => s.key === status);
  return (
    <div className="flex items-center gap-1 overflow-x-auto">
      {lifecycleStages.map((s, i) => (
        <div key={s.key} className="flex items-center gap-1">
          <div
            className={cn(
              "flex items-center gap-2 rounded-full border px-3 py-1 text-xs whitespace-nowrap",
              i < idx && "border-success/30 bg-success/10 text-success",
              i === idx && "border-primary/40 bg-primary/10 text-primary",
              i > idx && "border-border text-muted-foreground"
            )}
          >
            {i < idx ? <Check className="size-3" /> : <span className="font-mono">{i + 1}</span>}
            {s.label}
          </div>
          {i < lifecycleStages.length - 1 && <div className="h-px w-4 bg-border" />}
        </div>
      ))}
    </div>
  );
}

const TAB_META = [
  { key: "reqs", label: "Requirements", icon: <FileText className="size-4" /> },
  { key: "stories", label: "User Stories", icon: <ListTree className="size-4" /> },
  { key: "arch", label: "Architecture", icon: <Network className="size-4" /> },
  { key: "erd", label: "ER Diagram", icon: <Database className="size-4" /> },
  { key: "sprints", label: "Sprint Plan", icon: <CalendarRange className="size-4" /> },
  { key: "risk", label: "Risk", icon: <ShieldAlert className="size-4" /> },
  { key: "cost", label: "Cost & Timeline", icon: <DollarSign className="size-4" /> },
];

// editable — when true (TM view) shows edit/approve affordances.
export function ProjectPlan({ projectId, editable = false }: { projectId: string; editable?: boolean }) {
  const { getProject } = useApp();
  const p = getProject(projectId);
  const [tab, setTab] = useState("reqs");
  if (!p) return <div className="text-muted-foreground">Select a project first.</div>;

  return (
    <div className="space-y-4">
      <Panel className="p-5">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-3">
              <h2 className="font-display">{p.name}</h2>
              <StatusPill status={p.status} />
            </div>
            <p className="mt-1 max-w-2xl text-sm text-muted-foreground">{p.description}</p>
            <div className="mt-2 flex gap-4 text-xs text-muted-foreground font-mono">
              <span>{p.domain}</span>
              <span>Complexity: {p.complexity}</span>
            </div>
          </div>
          <AiTag label="Generated by Gemini · draft" />
        </div>
        <div className="mt-4">
          <Stepper status={p.status} />
        </div>
      </Panel>

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList className="flex-wrap h-auto">
          {TAB_META.map((t) => (
            <TabsTrigger key={t.key} value={t.key} className="gap-1.5">
              {t.icon} {t.label}
            </TabsTrigger>
          ))}
        </TabsList>

        <TabsContent value="reqs" className="mt-4">
          <div className="grid gap-4 lg:grid-cols-2">
            <PlanCard title="Functional Requirements" editable={editable}>
              <ul className="space-y-2">
                {aiRequirements.functional.map((r, i) => (
                  <li key={i} className="flex gap-2 text-sm">
                    <Mono className="text-primary">FR{i + 1}</Mono>
                    <span>{r}</span>
                  </li>
                ))}
              </ul>
            </PlanCard>
            <PlanCard title="Non-Functional Requirements" editable={editable}>
              <ul className="space-y-2">
                {aiRequirements.nonFunctional.map((r, i) => (
                  <li key={i} className="flex gap-2 text-sm">
                    <Mono className="text-chart-2">NFR{i + 1}</Mono>
                    <span>{r}</span>
                  </li>
                ))}
              </ul>
            </PlanCard>
          </div>
        </TabsContent>

        <TabsContent value="stories" className="mt-4">
          <div className="grid gap-4 md:grid-cols-3">
            {aiUserStories.map((e) => (
              <PlanCard key={e.epic} title={e.epic} editable={editable}>
                <ul className="space-y-3">
                  {e.stories.map((s, i) => (
                    <li key={i} className="rounded-md bg-muted/40 p-3 text-sm leading-relaxed">{s}</li>
                  ))}
                </ul>
              </PlanCard>
            ))}
          </div>
        </TabsContent>

        <TabsContent value="arch" className="mt-4">
          <PlanCard title="Recommended Architecture" editable={editable}>
            <div className="grid gap-3 sm:grid-cols-2">
              {aiArchitecture.map((a, i) => (
                <div key={i} className="flex items-center gap-3 rounded-md border border-border bg-muted/30 p-3 text-sm">
                  <span className="grid size-6 shrink-0 place-items-center rounded bg-primary/15 font-mono text-xs text-primary">{i + 1}</span>
                  {a}
                </div>
              ))}
            </div>
          </PlanCard>
        </TabsContent>

        <TabsContent value="erd" className="mt-4">
          <PlanCard title="Entity-Relationship Model" editable={editable}>
            <p className="mb-3 text-xs text-muted-foreground">Mermaid draft — refined by a human DB designer.</p>
            <pre className="overflow-x-auto rounded-md border border-border bg-[#0a0e14] p-4 font-mono text-xs leading-relaxed text-chart-1">
{erdMermaid}
            </pre>
          </PlanCard>
        </TabsContent>

        <TabsContent value="sprints" className="mt-4">
          <PlanCard title="Sprint Plan" editable={editable}>
            <div className="space-y-3">
              {[
                { n: 1, goal: "Auth, org setup, chart-of-accounts wizard", pts: 21, weeks: "Wk 1–2" },
                { n: 2, goal: "Ledger engine + immutable transaction model", pts: 26, weeks: "Wk 3–4" },
                { n: 3, goal: "Plaid ingest + reconciliation UI", pts: 24, weeks: "Wk 5–7" },
                { n: 4, goal: "Multi-currency + reporting endpoints", pts: 21, weeks: "Wk 8–9" },
                { n: 5, goal: "Gemini categorization + exports + hardening", pts: 18, weeks: "Wk 10–12" },
              ].map((s) => (
                <div key={s.n} className="flex items-center gap-4 rounded-md border border-border p-3">
                  <div className="grid size-10 shrink-0 place-items-center rounded-md bg-primary/10 font-display font-semibold text-primary">S{s.n}</div>
                  <div className="flex-1">
                    <div className="text-sm">{s.goal}</div>
                    <div className="text-xs text-muted-foreground font-mono">{s.weeks}</div>
                  </div>
                  <Mono className="text-sm text-muted-foreground">{s.pts} pts</Mono>
                </div>
              ))}
            </div>
          </PlanCard>
        </TabsContent>

        <TabsContent value="risk" className="mt-4">
          <PlanCard title="Risk Report" editable={editable}>
            <div className="mb-4 flex items-center gap-3 rounded-md border border-warning/25 bg-warning/10 p-3">
              <ShieldAlert className="size-5 text-warning" />
              <div>
                <div className="text-sm font-medium">Composite risk score: {p.riskScore}/100 (Moderate)</div>
                <div className="text-xs text-muted-foreground">Recalculated weekly from velocity, scope, and deadline proximity.</div>
              </div>
            </div>
            <div className="space-y-3">
              {aiRisks.map((r, i) => (
                <div key={i} className="rounded-md border border-border p-3">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium">{r.flag}</span>
                    <StatusPill status={r.severity} />
                  </div>
                  <p className="mt-1 text-sm text-muted-foreground">{r.note}</p>
                </div>
              ))}
            </div>
          </PlanCard>
        </TabsContent>

        <TabsContent value="cost" className="mt-4">
          <div className="grid gap-4 md:grid-cols-2">
            <PlanCard title="Budget Estimate" editable={editable}>
              <div className="text-3xl font-display font-semibold">{money(p.budgetLow)} – {money(p.budgetHigh)}</div>
              <p className="mt-1 text-xs text-muted-foreground">Estimated range, not a fixed quote. Spent to date: {money(p.spent)}.</p>
              <div className="mt-4">
                <ProgressBar value={(p.spent / p.budgetHigh) * 100} />
                <div className="mt-1 flex justify-between text-xs text-muted-foreground font-mono">
                  <span>{money(p.spent)} spent</span>
                  <span>{money(p.budgetHigh)} ceiling</span>
                </div>
              </div>
            </PlanCard>
            <PlanCard title="Timeline Prediction" editable={editable}>
              <div className="text-3xl font-display font-semibold">{p.timelineWeeks} weeks</div>
              <p className="mt-1 text-xs text-muted-foreground">
                {new Date(p.predictedStart).toLocaleDateString("en-US", { month: "short", day: "numeric" })} →{" "}
                {new Date(p.predictedEnd).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
              </p>
              <div className="mt-4 space-y-2">
                {p.team.slice(0, 4).map((id) => {
                  const m = personById(id)!;
                  return (
                    <div key={id} className="flex items-center justify-between text-sm">
                      <span>{m.name}</span>
                      <span className="text-muted-foreground font-mono">{m.role === "tm" ? "Lead" : m.rate ? money(m.rate) + "/hr" : "—"}</span>
                    </div>
                  );
                })}
              </div>
            </PlanCard>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}

function PlanCard({ title, children, editable }: { title: string; children: React.ReactNode; editable?: boolean }) {
  return (
    <Panel className="p-5">
      <div className="mb-3 flex items-center justify-between">
        <h3>{title}</h3>
        {editable && (
          <button className="flex items-center gap-1 rounded-md border border-border px-2 py-1 text-xs text-muted-foreground hover:text-foreground hover:border-primary/40">
            <Pencil className="size-3" /> Edit
          </button>
        )}
      </div>
      {children}
    </Panel>
  );
}
