export type Language = "en" | "ar";

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // General & Header
    "app.title": "DevPilot",
    "app.tagline": "AI Operating System for Software Agencies",
    "nav.dashboard": "Dashboard",
    "nav.projectPlan": "Project Plan",
    "nav.milestones": "Milestones",
    "nav.invoices": "Invoices",
    "nav.messages": "Messages",
    "nav.team": "Team",
    "nav.trustLayer": "Trust Layer",
    "nav.taskBoard": "Task Board",
    "nav.timeTracking": "Time Tracking",
    "nav.codeReviews": "Code Reviews",
    "nav.dailyLog": "Daily Log",
    "nav.standupCoach": "Standup Coach",
    "nav.myProfile": "My Profile",
    "nav.overview": "Overview",
    "nav.aiPlanReview": "AI Plan Review",
    "nav.assignments": "Assignments",
    "nav.prReviews": "PR Reviews",
    "nav.reports": "Reports",
    "nav.analytics": "Analytics",
    "nav.users": "Users",
    "nav.projects": "Projects",
    "nav.subscriptions": "Subscriptions",
    "nav.support": "Support",
    "nav.platform": "Platform",

    // Roles
    "role.client": "Client",
    "role.developer": "Developer",
    "role.tm": "Technical Manager",
    "role.admin": "Admin",
    "role.switch": "Switch View",

    // Search & Topbar
    "topbar.search": "Search projects, tasks, invoices...",
    "topbar.notifications": "Notifications",
    "topbar.aiBadge": "Llama 3.3 · Groq",
    "topbar.noNotifications": "No unread notifications",

    // AI Assistant
    "ai.title": "DevPilot AI Copilot",
    "ai.placeholder": "Ask about projects, tasks, code reviews, or estimates...",
    "ai.disclaimer": "Powered by Groq · Llama 3.3 70B",
    "ai.suggested.1": "Summarize project status",
    "ai.suggested.2": "Generate sprint report",
    "ai.suggested.3": "Check risk factors",

    // Client Dashboard & Projects
    "client.projects": "Projects",
    "client.newProject": "New Project",
    "client.activeProjects": "Active Projects",
    "client.totalSpent": "Total Spent",
    "client.completedProjects": "Completed",
    "client.createProjectTitle": "Create New AI Project Plan",
    "client.createProjectDesc": "Describe your software concept. Llama 3.3 will automatically generate architecture, sprint plans, requirements, and cost estimates.",
    "client.projectName": "Project Name",
    "client.domain": "Domain / Category",
    "client.description": "Detailed Project Description",
    "client.generateBtn": "Generate Technical Plan with AI",
    "client.cancel": "Cancel",
    "client.generating": "Llama 3.3 is analyzing your project...",
    "client.generatingSub": "Generating requirements, architecture, risks & sprint plan",
    "client.errorTitle": "Plan generation failed",
    "client.errorSub": "Check your connection or API key and try creating the project again.",
    "client.retry": "Retry Generation",

    // Project Plan Tabs
    "tab.requirements": "Requirements",
    "tab.userStories": "User Stories",
    "tab.architecture": "Architecture",
    "tab.erd": "ERD Model",
    "tab.sprints": "Sprint Plan",
    "tab.risk": "Risks & Flags",
    "tab.cost": "Cost & Timeline",

    // Requirements Tab
    "req.functional": "Functional Requirements",
    "req.nonFunctional": "Non-Functional Requirements",
    "req.userStoriesTitle": "Epic & User Stories",

    // Architecture & ERD
    "arch.title": "Proposed Technical Architecture",
    "erd.title": "Entity-Relationship Model",
    "erd.subtitle": "Mermaid diagram — generated by Llama 3.3 AI",

    // Sprints & Risk
    "sprint.title": "AI-Generated Sprint Roadmap",
    "sprint.pts": "pts",
    "risk.title": "AI Risk Radar & Mitigation",
    "risk.severity": "Severity",

    // Cost & Timeline
    "cost.budgetTitle": "Budget Estimate",
    "cost.budgetSub": "AI estimate — not a fixed quote.",
    "cost.spent": "spent",
    "cost.ceiling": "ceiling",
    "cost.timelineTitle": "Timeline Prediction",

    // Milestones & Invoices
    "milestones.title": "Milestones & Deliverables",
    "milestones.totalContract": "Total Contract",
    "milestones.paid": "Paid to Date",
    "milestones.inReview": "In Review",
    "invoices.title": "Invoices & Payments",
    "invoices.payNow": "Pay Now",
    "invoices.due": "Due",
    "invoices.paid": "Paid",

    // Developer Views
    "dev.taskBoard": "Task Board",
    "dev.todo": "To Do",
    "dev.inProgress": "In Progress",
    "dev.review": "In Review",
    "dev.done": "Done",
    "dev.logHours": "Log Hours",
    "dev.timeTracking": "Time Tracking",
    "dev.codeReviews": "Code Reviews & PRs",
    "dev.qualityScore": "Code Quality Score",

    // Technical Manager (TM) Views
    "tm.overview": "Technical Manager Overview",
    "tm.aiPlanReview": "AI Plan Review",
    "tm.approvePlan": "Approve Technical Plan",
    "tm.requestChanges": "Request Changes",
    "tm.riskRadar": "Risk Radar",
    "tm.teamAllocation": "Team Resource Allocation",

    // Admin Views
    "admin.analytics": "Platform Analytics",
    "admin.mrr": "Monthly Recurring Revenue",
    "admin.activeSubscriptions": "Active Subscriptions",
    "admin.platformUsage": "Platform Usage",
    "admin.tierManagement": "Tier & Subscription Management",

    // Landing Page
    "landing.badge": "DevPilot Operating System v2.0",
    "landing.title": "The AI-Powered Software Agency Platform",
    "landing.subtitle": "Automate project intake, generate technical roadmaps in seconds with Llama 3.3, and run transparent client-developer workflows.",
    "landing.enterApp": "Launch Workspace",
    "landing.viewPricing": "View Pricing Tiers",
    "landing.featuresTitle": "Built for Modern Tech Agencies & Clients",
    "landing.featuresSub": "Replace scattered tools with a unified AI-driven operating system.",
    "landing.pricingTitle": "Transparent, Scale-Ready Pricing",
    "landing.trustTitle": "DevPilot Trust & Security Layer",
    "landing.trustSub": "Enterprise-grade governance, audit trails, and automated compliance.",
    "landing.footerRights": "All rights reserved.",
  },
  ar: {
    // General & Header
    "app.title": "DevPilot",
    "app.tagline": "نظام تشغيل وإدارة شركات البرمجيات بالذكاء الاصطناعي",
    "nav.dashboard": "لوحة التحكم",
    "nav.projectPlan": "خطة المشروع",
    "nav.milestones": "المراحل الرئيسية",
    "nav.invoices": "الفواتير",
    "nav.messages": "الرسائل",
    "nav.team": "فريق العمل",
    "nav.trustLayer": "طبقة الثقة والأمان",
    "nav.taskBoard": "لوحة المهام",
    "nav.timeTracking": "تتبع الوقت",
    "nav.codeReviews": "مراجعة الكود",
    "nav.dailyLog": "السجل اليومي",
    "nav.standupCoach": "مدرب الاجتماعات",
    "nav.myProfile": "ملفي الشخصي",
    "nav.overview": "نظرة عامة",
    "nav.aiPlanReview": "مراجعة خطة الذكاء الاصطناعي",
    "nav.assignments": "التكليفات",
    "nav.prReviews": "مراجعات PR",
    "nav.reports": "التقارير",
    "nav.analytics": "التحليلات",
    "nav.users": "المستخدمين",
    "nav.projects": "المشاريع",
    "nav.subscriptions": "الاشتراكات",
    "nav.support": "الدعم الفني",
    "nav.platform": "المنصة",

    // Roles
    "role.client": "العميل",
    "role.developer": "المطور",
    "role.tm": "المدير التقني",
    "role.admin": "المسؤول",
    "role.switch": "تبديل الواجهة",

    // Search & Topbar
    "topbar.search": "البحث في المشاريع، المهام، الفواتير...",
    "topbar.notifications": "الإشعارات",
    "topbar.aiBadge": "Llama 3.3 · Groq",
    "topbar.noNotifications": "لا توجد إشعارات غير قراءة",

    // AI Assistant
    "ai.title": "مساعد DevPilot الذكي",
    "ai.placeholder": "اسأل عن المشاريع، المهام، مراجعات الكود، أو التقديرات...",
    "ai.disclaimer": "مدعوم بواسطة Groq · Llama 3.3 70B",
    "ai.suggested.1": "تلخيص حالة المشروع",
    "ai.suggested.2": "توليد تقرير السبرنت",
    "ai.suggested.3": "فحص عوامل المخاطرة",

    // Client Dashboard & Projects
    "client.projects": "المشاريع",
    "client.newProject": "+ مشروع جديد",
    "client.activeProjects": "المشاريع النشطة",
    "client.totalSpent": "إجمالي المصروفات",
    "client.completedProjects": "المكتملة",
    "client.createProjectTitle": "إنشاء خطة مشروع جديدة بالذكاء الاصطناعي",
    "client.createProjectDesc": "اكتب فكرة مشروعك. سيقوم Llama 3.3 بتوليد البنية الهندسية، خطة السبرنتات، المتطلبات، وتقديرات التكلفة تلقائياً.",
    "client.projectName": "اسم المشروع",
    "client.domain": "المجال / التصنيف",
    "client.description": "وصف تفصيلي للمشروع",
    "client.generateBtn": "توليد الخطة التقنية بالذكاء الاصطناعي",
    "client.cancel": "إلغاء",
    "client.generating": "جاري تحليل مشروعك بواسطة Llama 3.3...",
    "client.generatingSub": "جاري توليد المتطلبات، البنية الهندسية، المخاطر، وخطة السبرنتات",
    "client.errorTitle": "فشل توليد الخطة",
    "client.errorSub": "تحقق من الاتصال بالإنترنت أو مفتاح الـ API وحاول مرة أخرى.",
    "client.retry": "إعادة محاولة التوليد",

    // Project Plan Tabs
    "tab.requirements": "المتطلبات",
    "tab.userStories": "قصص المستخدم",
    "tab.architecture": "البنية الهندسية",
    "tab.erd": "مخطط قاعدة البيانات ERD",
    "tab.sprints": "خطة السبرنتات",
    "tab.risk": "المخاطر والتحذيرات",
    "tab.cost": "التكلفة والجدول الزمني",

    // Requirements Tab
    "req.functional": "المتطلبات الوظيفية (Functional)",
    "req.nonFunctional": "المتطلبات غير الوظيفية (Non-Functional)",
    "req.userStoriesTitle": "الملاحم وقصص المستخدم (User Stories)",

    // Architecture & ERD
    "arch.title": "البنية الهندسية والتقنيات المقترحة",
    "erd.title": "مخطط كيانات قاعدة البيانات (ERD)",
    "erd.subtitle": "رسم Mermaid بياني — مُنشأ بواسطة الذكاء الاصطناعي Llama 3.3",

    // Sprints & Risk
    "sprint.title": "خطة السبرنتات المُنشأة بالذكاء الاصطناعي",
    "sprint.pts": "نقطة",
    "risk.title": "رادار تقييم المخاطر وتجنبها",
    "risk.severity": "مستوى الخطورة",

    // Cost & Timeline
    "cost.budgetTitle": "تقدير الميزانية",
    "cost.budgetSub": "تقدير الذكاء الاصطناعي — ليس عرض سعر ثابت.",
    "cost.spent": "المصروف",
    "cost.ceiling": "الحد الأقصى",
    "cost.timelineTitle": "توقع الجدول الزمني",

    // Milestones & Invoices
    "milestones.title": "المراحل الرئيسية والتسليمات",
    "milestones.totalContract": "إجمالي العقد",
    "milestones.paid": "المدفوع حتى الآن",
    "milestones.inReview": "قيد المراجعة",
    "invoices.title": "الفواتير المدفوعات",
    "invoices.payNow": "ادفع الآن",
    "invoices.due": "مستحقة",
    "invoices.paid": "مدفوعة",

    // Developer Views
    "dev.taskBoard": "لوحة إدارة المهام",
    "dev.todo": "معلقة (To Do)",
    "dev.inProgress": "قيد التنفيذ (In Progress)",
    "dev.review": "قيد المراجعة (Review)",
    "dev.done": "مكتملة (Done)",
    "dev.logHours": "تسجيل الساعات",
    "dev.timeTracking": "تتبع أوقات العمل",
    "dev.codeReviews": "مراجعات الكود و PRs",
    "dev.qualityScore": "درجة جودة الكود",

    // Technical Manager (TM) Views
    "tm.overview": "نظرة عامة للمدير التقني",
    "tm.aiPlanReview": "مراجعة خطة الذكاء الاصطناعي",
    "tm.approvePlan": "اعتماد الخطة التقنية",
    "tm.requestChanges": "طلب تعديلات",
    "tm.riskRadar": "رادار المخاطر",
    "tm.teamAllocation": "توزيع الموارد والفريق",

    // Admin Views
    "admin.analytics": "تحليلات المنصة",
    "admin.mrr": "الإيرادات الشهرية المتكررة (MRR)",
    "admin.activeSubscriptions": "الاشتراكات النشطة",
    "admin.platformUsage": "استخدام المنصة",
    "admin.tierManagement": "إدارة الباقات والاشتراكات",

    // Landing Page
    "landing.badge": "نظام DevPilot الإصدار v2.0",
    "landing.title": "منصة تشغيل وإدارة شركات وتطوير البرمجيات بالذكاء الاصطناعي",
    "landing.subtitle": "أتمتة استلام المشاريع، توليد الخرائط التقنية في ثوانٍ بواسطة Llama 3.3، وإدارة بيئة عمل شفافة بين العملاء والمطورين.",
    "landing.enterApp": "دخول مساحة العمل",
    "landing.viewPricing": "استعراض خطط الأسعار",
    "landing.featuresTitle": "صُمم لشركات البرمجيات الحديثة والعملاء",
    "landing.featuresSub": "استبدل أدواتك المتشتتة بنظام موحد يديره الذكاء الاصطناعي.",
    "landing.pricingTitle": "خطط أسعار شفافة وجاهزة للنمو",
    "landing.trustTitle": "طبقة الثقة والأمان في DevPilot",
    "landing.trustSub": "حكومة تقنية على مستوى المؤسسات، سجلات تدقيق متكاملة، وحماية للبيانات.",
    "landing.footerRights": "جميع الحقوق محفوظة.",
  },
};
